version: "3.7"
services:
  api_service:
    build:
      context: fastapi
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir ./code"
    container_name: fastapi
    hostname: fastapi
    volumes:
      - ./fastapi:/code
    networks:
      - efk-net
      
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/log:/var/log/nginx
    networks:
      - efk-net
    depends_on:
      - api_service

  fluentd:
    build: ./fluentd
    container_name: fluentd
    hostname: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./nginx/log:/var/log/nginx
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - efk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    hostname: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - efk-net

volumes:
  esdata:
    driver: local

networks:
  efk-net:
    external: true